### ISSUE TITLE
Use https instead of http

### ISSUE THREAD

**Issue by samdupton** [BlackHolePerturbationToolkit/blackholeperturbationtoolkit.github.io#1]
Automatically redirect users from the non-secure version of the site to the secure version of the site.

**Comment by barrywardell** [comment]
This is now set for all components of the toolkit using the "Enforce HTTPS" option.

**Comment by samdupton** [comment]
Currently build.bhptoolkit.org refuses requests when attempting to connect via https but accepts them via http.
