### ISSUE TITLE
Switch build.bhptoolkit.org from http to https

### ISSUE THREAD

**Issue by samdupton** [BlackHolePerturbationToolkit/blackholeperturbationtoolkit.github.io#2]
Currently build.bhptoolkit.org refuses requests when attempting to connect via https but accepts them via http.

_Originally posted by @samdupton in https://github.com/BlackHolePerturbationToolkit/blackholeperturbationtoolkit.github.io/issues/1#issuecomment-475199523_

**Comment by barrywardell** [comment]
build.bhptoolkit.org now only connects via https with a redirect if you try to access via http.
